tests yet more lang.neutral

diff --git a/t/regression-tests b/t/regression-tests
--- a/t/regression-tests
+++ b/t/regression-tests
@@ -1,4 +1,11 @@
 #!/bin/bash
 
-# run with -f to show only failing tests
-exec -a "$(basename $0)" bash $(dirname $0)/wiki-tests -u "$@" Regression sme nob
+# Run with -f to show only failing tests
+
+set -e -u
+
+source "$(dirname $0)"/config.sh
+
+for pair in "${PAIRS[@]}"; do
+    bash "$(dirname $0)"/wiki-tests -u "$@" Regression "${pair}"
+done
